cfe list deployment

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -72,3 +72,18 @@ jobs:
           path: check
 
 
+  aggregate:
+    name: R-CMD-check
+    runs-on: ubuntu-latest
+    needs:
+      - R-CMD-check
+    if: ${{ always() }}
+    steps:
+      - name: Aggregate matrix result
+        run: |
+          if [ "${{ needs.R-CMD-check.result }}" != "success" ]; then
+            echo "Matrix job failed" >&2
+            exit 1
+          fi
+          echo "All matrix jobs passed"
+
